### PR TITLE
Add seaborn as dependency and merge FINAL notebook

### PR DESCRIPTION
**Pull request by felipepaes**

### CODE REVIEW

**Review by esloch — APPROVED** [review]
LGTM!

**Comment by esloch** [comment]
@felipepaes. Is it ready for merging?

**Comment by felipepaes** [comment]
Hey @esloch !

Yes, there is some refine to do, but the overall project structure is complete.

I left some TODOS which are:
- After the Random Forest training in part 2:
    - Briefly summarize the results obtained.
    - Highlight the achievements from the research/study.
    - Indicate limitations and reareas for consideration.
- In part 3 I've already created a dataframe with the metrics from every algorythm used
    - Include at least 3 more examples using the predictor
    - it would be nice to have a bar chart comparing the four
image

I didn't have the time to add these changes yet. Once it's finished, I intend to train the models with the complete dataset (including all four states) and update it with another PR.

If you'd like to wait until those modifications are complete, I can share my forked repo with the team for collaboration, and we can merge the final version afterward.

**Review by esloch — APPROVED** [review]
> Hey @esloch !
> 
> Yes, there is some refine to do, but the overall project structure is complete.
> 
> I left some TODOS which are:
> 
>     * After the Random Forest training in part 2:
>       
>       * Briefly summarize the results obtained.
>       * Highlight the achievements from the research/study.
>       * Indicate limitations and reareas for consideration.
> 
>     * In part 3 I've already created a dataframe with the metrics from every algorythm used
>       
>       * Include at least 3 more examples using the predictor
>       * it would be nice to have a bar chart comparing the four
>         image
> 
> 
> I didn't have the time to add these changes yet. Once it's finished, I intend to train the models with the complete dataset (including all four states) and update it with another PR.
> 
> If you'd like to wait until those modifications are complete, I can share my forked repo with the team for collaboration, and we can merge the final version afterward.

Thanks @felipepaes! You can open an issue for these additional implementations.
Merged!

**Pull request merged**
